# Generated from SRR2.vcxproj by tools/gen_cmake_sources.py.
set(SRR2_SOURCES
    ../game/ai/actionbuttonhandler.cpp
    ../game/ai/actionbuttonmanager.cpp
    ../game/ai/actor/ActorAnimationUFO.cpp
    ../game/ai/actor/actor.cpp
    ../game/ai/actor/actoranimationwasp.cpp
    ../game/ai/actor/actordsg.cpp
    ../game/ai/actor/actormanager.cpp
    ../game/ai/actor/attackbehaviour.cpp
    ../game/ai/actor/attractionbehaviour.cpp
    ../game/ai/actor/cutcambehaviour.cpp
    ../game/ai/actor/evasionbehaviour.cpp
    ../game/ai/actor/flyingactor.cpp
    ../game/ai/actor/intersectionlist.cpp
    ../game/ai/actor/projectile.cpp
    ../game/ai/actor/projectiledsg.cpp
    ../game/ai/actor/spawnpoint.cpp
    ../game/ai/actor/stunnedbehaviour.cpp
    ../game/ai/actor/ufoattackbehaviour.cpp
    ../game/ai/actor/ufobeamalwaysonbehaviour.cpp
    ../game/ai/actor/ufobehaviour.cpp
    ../game/ai/automaticdoor.cpp
    ../game/ai/playanimonce.cpp
    ../game/ai/sequencer/action.cpp
    ../game/ai/sequencer/actioncontroller.cpp
    ../game/ai/sequencer/sequencer.cpp
    ../game/ai/sequencer/task.cpp
    ../game/ai/state.cpp
    ../game/ai/statemanager.cpp
    ../game/ai/vehicle/chaseai.cpp
    ../game/ai/vehicle/potentialfield.cpp
    ../game/ai/vehicle/potentials.cpp
    ../game/ai/vehicle/trafficai.cpp
    ../game/ai/vehicle/vehicleai.cpp
    ../game/ai/vehicle/vehicleairender.cpp
    ../game/ai/vehicle/waypointai.cpp
    ../game/atc/atcloader.cpp
    ../game/atc/atcmanager.cpp
    ../game/camera/animatedcam.cpp
    ../game/camera/bumpercam.cpp
    ../game/camera/chasecam.cpp
    ../game/camera/conversationcam.cpp
    ../game/camera/debugcam.cpp
    ../game/camera/firstpersoncam.cpp
    ../game/camera/followcam.cpp
    ../game/camera/kullcam.cpp
    ../game/camera/pccam.cpp
    ../game/camera/railcam.cpp
    ../game/camera/relativeanimatedcam.cpp
    ../game/camera/reversecam.cpp
    ../game/camera/sinecosshaker.cpp
    ../game/camera/snapshotcam.cpp
    ../game/camera/staticcam.cpp
    ../game/camera/supercam.cpp
    ../game/camera/supercamcentral.cpp
    ../game/camera/supercamcontroller.cpp
    ../game/camera/supercammanager.cpp
    ../game/camera/supersprintcam.cpp
    ../game/camera/surveillancecam.cpp
    ../game/camera/trackercam.cpp
    ../game/camera/walkercam.cpp
    ../game/camera/wrecklesscam.cpp
    ../game/camera/wrecklesseventlistener.cpp
    ../game/cards/bonuscard.cpp
    ../game/cards/card.cpp
    ../game/cards/cardgallery.cpp
    ../game/cards/cardsdb.cpp
    ../game/cards/collectorcard.cpp
    ../game/cheats/cheatinputhandler.cpp
    ../game/cheats/cheatinputsystem.cpp
    ../game/cheats/cheats.cpp
    ../game/console/console.cpp
    ../game/console/debugconsolecallback.cpp
    ../game/console/fbstricmp.cpp
    ../game/console/nameinsensitive.cpp
    ../game/console/upcase.cpp
    ../game/contexts/bootupcontext.cpp
    ../game/contexts/context.cpp
    ../game/contexts/demo/democontext.cpp
    ../game/contexts/demo/loadingdemocontext.cpp
    ../game/contexts/entrycontext.cpp
    ../game/contexts/exitcontext.cpp
    ../game/contexts/frontendcontext.cpp
    ../game/contexts/gameplay/gameplaycontext.cpp
    ../game/contexts/gameplay/loadinggameplaycontext.cpp
    ../game/contexts/loadingcontext.cpp
    ../game/contexts/pausecontext.cpp
    ../game/contexts/playingcontext.cpp
    ../game/contexts/supersprint/loadingsupersprintcontext.cpp
    ../game/contexts/supersprint/supersprintcontext.cpp
    ../game/contexts/supersprint/supersprintfecontext.cpp
    ../game/data/PersistentWorldManager.cpp
    ../game/data/config/configstring.cpp
    ../game/data/config/gameconfigmanager.cpp
    ../game/data/gamedatamanager.cpp
    ../game/data/memcard/memorycardmanager.cpp
    ../game/data/savegameinfo.cpp
    ../game/debug/debuginfo.cpp
    ../game/debug/profiler.cpp
    ../game/debug/section.cpp
    ../game/events/eventlistener.cpp
    ../game/events/eventmanager.cpp
    ../game/font/defaultfont.cpp
    ../game/gameflow/gameflow.cpp
    ../game/input/FEMouse.cpp
    ../game/input/Gamepad.cpp
    ../game/input/Keyboard.cpp
    ../game/input/Mouse.cpp
    ../game/input/MouseCursor.cpp
    ../game/input/RealController.cpp
    ../game/input/SteeringWheel.cpp
    ../game/input/button.cpp
    ../game/input/inputmanager.cpp
    ../game/input/mappable.cpp
    ../game/input/mapper.cpp
    ../game/input/rumbleeffect.cpp
    ../game/input/rumblewin32.cpp
    ../game/input/usercontrollerWin32.cpp
    ../game/input/virtualinputs.cpp
    ../game/interiors/interiormanager.cpp
    ../game/loading/cameradataloader.cpp
    ../game/loading/cementfilehandler.cpp
    ../game/loading/choreofilehandler.cpp
    ../game/loading/consolefilehandler.cpp
    ../game/loading/filehandlerfactory.cpp
    ../game/loading/iconfilehandler.cpp
    ../game/loading/intersectionloader.cpp
    ../game/loading/loadingmanager.cpp
    ../game/loading/locatorloader.cpp
    ../game/loading/p3dfilehandler.cpp
    ../game/loading/pathloader.cpp
    ../game/loading/roaddatasegmentloader.cpp
    ../game/loading/roadloader.cpp
    ../game/loading/scroobyfilehandler.cpp
    ../game/loading/soundfilehandler.cpp
    ../game/main/commandlineoptions.cpp
    ../game/main/game.cpp
    ../game/main/main.cpp
    ../game/main/pchsrr2.cpp
    ../game/main/sdlplatform.cpp
    ../game/main/singletons.cpp
    ../game/main/tuidunaligned.cpp
    ../game/memory/classsizetracker.cpp
    ../game/memory/createheap.cpp
    ../game/memory/leakdetection.cpp
    ../game/memory/memorypool.cpp
    ../game/memory/memoryutilities.cpp
    ../game/memory/propstats.cpp
    ../game/memory/srrmemory.cpp
    ../game/meta/actioneventlocator.cpp
    ../game/meta/carstartlocator.cpp
    ../game/meta/directionallocator.cpp
    ../game/meta/eventlocator.cpp
    ../game/meta/fovlocator.cpp
    ../game/meta/interiorentrancelocator.cpp
    ../game/meta/locator.cpp
    ../game/meta/occlusionlocator.cpp
    ../game/meta/recttriggervolume.cpp
    ../game/meta/scriptlocator.cpp
    ../game/meta/spheretriggervolume.cpp
    ../game/meta/splinelocator.cpp
    ../game/meta/staticcamlocator.cpp
    ../game/meta/triggerlocator.cpp
    ../game/meta/triggervolume.cpp
    ../game/meta/triggervolumetracker.cpp
    ../game/meta/zoneeventlocator.cpp
    ../game/mission/animatedicon.cpp
    ../game/mission/bonusmissioninfo.cpp
    ../game/mission/charactersheet/charactersheetmanager.cpp
    ../game/mission/conditions/damagecondition.cpp
    ../game/mission/conditions/followcondition.cpp
    ../game/mission/conditions/getoutofcarcondition.cpp
    ../game/mission/conditions/keepbarrelcondition.cpp
    ../game/mission/conditions/leaveinteriorcondition.cpp
    ../game/mission/conditions/missioncondition.cpp
    ../game/mission/conditions/notabductedcondition.cpp
    ../game/mission/conditions/outofboundscondition.cpp
    ../game/mission/conditions/positioncondition.cpp
    ../game/mission/conditions/racecondition.cpp
    ../game/mission/conditions/timeoutcondition.cpp
    ../game/mission/conditions/vehiclecarryingstateprop.cpp
    ../game/mission/conditions/vehiclecondition.cpp
    ../game/mission/gameplaymanager.cpp
    ../game/mission/haspresentationinfo.cpp
    ../game/mission/mission.cpp
    ../game/mission/missionmanager.cpp
    ../game/mission/missionscriptloader.cpp
    ../game/mission/missionstage.cpp
    ../game/mission/nocopbonusobjective.cpp
    ../game/mission/nodamagebonusobjective.cpp
    ../game/mission/objectives/buycarobjective.cpp
    ../game/mission/objectives/buyskinobjective.cpp
    ../game/mission/objectives/coinobjective.cpp
    ../game/mission/objectives/collectdumpedobjective.cpp
    ../game/mission/objectives/collectibleobjective.cpp
    ../game/mission/objectives/deliveryobjective.cpp
    ../game/mission/objectives/destroybossobjective.cpp
    ../game/mission/objectives/destroyobjective.cpp
    ../game/mission/objectives/dialogueobjective.cpp
    ../game/mission/objectives/fmvobjective.cpp
    ../game/mission/objectives/followobjective.cpp
    ../game/mission/objectives/getinobjective.cpp
    ../game/mission/objectives/gooutsideobjective.cpp
    ../game/mission/objectives/gotoobjective.cpp
    ../game/mission/objectives/interiorobjective.cpp
    ../game/mission/objectives/loadvehicleobjective.cpp
    ../game/mission/objectives/loseobjective.cpp
    ../game/mission/objectives/missionobjective.cpp
    ../game/mission/objectives/pickupitemobjective.cpp
    ../game/mission/objectives/raceobjective.cpp
    ../game/mission/objectives/talktoobjective.cpp
    ../game/mission/objectives/timerobjective.cpp
    ../game/mission/racepositionbonusobjective.cpp
    ../game/mission/respawnmanager/respawnentity.cpp
    ../game/mission/respawnmanager/respawnmanager.cpp
    ../game/mission/rewards/merchandise.cpp
    ../game/mission/rewards/reward.cpp
    ../game/mission/rewards/rewardsmanager.cpp
    ../game/mission/safezone/safezone.cpp
    ../game/mission/statepropcollectible.cpp
    ../game/mission/timeremainbonusobjective.cpp
    ../game/mission/ufo/tractorbeam.cpp
    ../game/mission/ufo/ufo.cpp
    ../game/pedpaths/path.cpp
    ../game/pedpaths/pathmanager.cpp
    ../game/pedpaths/pathsegment.cpp
    ../game/presentation/animplayer.cpp
    ../game/presentation/blinker.cpp
    ../game/presentation/cameraplayer.cpp
    ../game/presentation/fmvplayer/fmvplayer.cpp
    ../game/presentation/fmvplayer/fmvuserinputhandler.cpp
    ../game/presentation/gui/backend/guimanagerbackend.cpp
    ../game/presentation/gui/backend/guiscreendemo.cpp
    ../game/presentation/gui/backend/guiscreenloading.cpp
    ../game/presentation/gui/backend/guiscreenloadingfe.cpp
    ../game/presentation/gui/bootup/guimanagerbootup.cpp
    ../game/presentation/gui/bootup/guimanagerlanguage.cpp
    ../game/presentation/gui/bootup/guiscreenbootupload.cpp
    ../game/presentation/gui/bootup/guiscreenlanguage.cpp
    ../game/presentation/gui/bootup/guiscreenlicense.cpp
    ../game/presentation/gui/frontend/guimanagerfrontend.cpp
    ../game/presentation/gui/frontend/guiscreencardgallery.cpp
    ../game/presentation/gui/frontend/guiscreencontrollerWin32.cpp
    ../game/presentation/gui/frontend/guiscreendisplay.cpp
    ../game/presentation/gui/frontend/guiscreenloadgame.cpp
    ../game/presentation/gui/frontend/guiscreenmainmenu.cpp
    ../game/presentation/gui/frontend/guiscreenmissiongallery.cpp
    ../game/presentation/gui/frontend/guiscreenoptions.cpp
    ../game/presentation/gui/frontend/guiscreenplaymovie.cpp
    ../game/presentation/gui/frontend/guiscreenscrapbook.cpp
    ../game/presentation/gui/frontend/guiscreenscrapbookcontents.cpp
    ../game/presentation/gui/frontend/guiscreenscrapbookstats.cpp
    ../game/presentation/gui/frontend/guiscreenskingallery.cpp
    ../game/presentation/gui/frontend/guiscreensound.cpp
    ../game/presentation/gui/frontend/guiscreensplash.cpp
    ../game/presentation/gui/frontend/guiscreenvehiclegallery.cpp
    ../game/presentation/gui/frontend/guiscreenviewcredits.cpp
    ../game/presentation/gui/frontend/guiscreenviewmovies.cpp
    ../game/presentation/gui/guientity.cpp
    ../game/presentation/gui/guimanager.cpp
    ../game/presentation/gui/guimenu.cpp
    ../game/presentation/gui/guimenuitem.cpp
    ../game/presentation/gui/guiscreen.cpp
    ../game/presentation/gui/guiscreenmemcardcheck.cpp
    ../game/presentation/gui/guiscreenmemorycard.cpp
    ../game/presentation/gui/guiscreenmessage.cpp
    ../game/presentation/gui/guiscreenprompt.cpp
    ../game/presentation/gui/guisystem.cpp
    ../game/presentation/gui/guitextbible.cpp
    ../game/presentation/gui/guiuserinputhandler.cpp
    ../game/presentation/gui/guiwindow.cpp
    ../game/presentation/gui/ingame/guimanageringame.cpp
    ../game/presentation/gui/ingame/guiscreencreditspostfmv.cpp
    ../game/presentation/gui/ingame/guiscreenhastransitions.cpp
    ../game/presentation/gui/ingame/guiscreenhud.cpp
    ../game/presentation/gui/ingame/guiscreeniriswipe.cpp
    ../game/presentation/gui/ingame/guiscreenletterbox.cpp
    ../game/presentation/gui/ingame/guiscreenlevelend.cpp
    ../game/presentation/gui/ingame/guiscreenlevelstats.cpp
    ../game/presentation/gui/ingame/guiscreenmissionbase.cpp
    ../game/presentation/gui/ingame/guiscreenmissionload.cpp
    ../game/presentation/gui/ingame/guiscreenmissionover.cpp
    ../game/presentation/gui/ingame/guiscreenmissionselect.cpp
    ../game/presentation/gui/ingame/guiscreenmissionsuccess.cpp
    ../game/presentation/gui/ingame/guiscreenmultihud.cpp
    ../game/presentation/gui/ingame/guiscreenpause.cpp
    ../game/presentation/gui/ingame/guiscreenpausecontroller.cpp
    ../game/presentation/gui/ingame/guiscreenpausedisplay.cpp
    ../game/presentation/gui/ingame/guiscreenpausemission.cpp
    ../game/presentation/gui/ingame/guiscreenpauseoptions.cpp
    ../game/presentation/gui/ingame/guiscreenpausesettings.cpp
    ../game/presentation/gui/ingame/guiscreenpausesound.cpp
    ../game/presentation/gui/ingame/guiscreenpausesunday.cpp
    ../game/presentation/gui/ingame/guiscreenphonebooth.cpp
    ../game/presentation/gui/ingame/guiscreenpurchaserewards.cpp
    ../game/presentation/gui/ingame/guiscreenrewards.cpp
    ../game/presentation/gui/ingame/guiscreensavegame.cpp
    ../game/presentation/gui/ingame/guiscreentutorial.cpp
    ../game/presentation/gui/ingame/guiscreenviewcards.cpp
    ../game/presentation/gui/ingame/hudevents/hudcardcollected.cpp
    ../game/presentation/gui/ingame/hudevents/hudcoincollected.cpp
    ../game/presentation/gui/ingame/hudevents/hudcountdown.cpp
    ../game/presentation/gui/ingame/hudevents/hudeventhandler.cpp
    ../game/presentation/gui/ingame/hudevents/hudhitnrun.cpp
    ../game/presentation/gui/ingame/hudevents/huditemdropped.cpp
    ../game/presentation/gui/ingame/hudevents/hudmissionobjective.cpp
    ../game/presentation/gui/ingame/hudevents/hudmissionprogress.cpp
    ../game/presentation/gui/ingame/hudevents/hudwaspdestroyed.cpp
    ../game/presentation/gui/minigame/guimanagerminigame.cpp
    ../game/presentation/gui/minigame/guiscreenminihud.cpp
    ../game/presentation/gui/minigame/guiscreenminimenu.cpp
    ../game/presentation/gui/minigame/guiscreenminipause.cpp
    ../game/presentation/gui/minigame/guiscreenminisummary.cpp
    ../game/presentation/gui/utility/hudmap.cpp
    ../game/presentation/gui/utility/hudmapcam.cpp
    ../game/presentation/gui/utility/numerictext.cpp
    ../game/presentation/gui/utility/scrollingtext.cpp
    ../game/presentation/gui/utility/slider.cpp
    ../game/presentation/gui/utility/specialfx.cpp
    ../game/presentation/gui/utility/teletypetext.cpp
    ../game/presentation/gui/utility/transitions.cpp
    ../game/presentation/language.cpp
    ../game/presentation/mouthflapper.cpp
    ../game/presentation/nisplayer.cpp
    ../game/presentation/playerdrawable.cpp
    ../game/presentation/presentation.cpp
    ../game/presentation/presentationanimator.cpp
    ../game/presentation/presevents/fmvevent.cpp
    ../game/presentation/presevents/nisevent.cpp
    ../game/presentation/presevents/presentationevent.cpp
    ../game/presentation/presevents/transevent.cpp
    ../game/presentation/simpleanimationplayer.cpp
    ../game/presentation/transitionplayer.cpp
    ../game/presentation/tutorialmanager.cpp
    ../game/render/Culling/BoxPts.cpp
    ../game/render/Culling/Cell.cpp
    ../game/render/Culling/CellBlock.cpp
    ../game/render/Culling/CoordSubList.cpp
    ../game/render/Culling/CullData.cpp
    ../game/render/Culling/HexahedronP.cpp
    ../game/render/Culling/ISpatialProxy.cpp
    ../game/render/Culling/OctTreeData.cpp
    ../game/render/Culling/OctTreeNode.cpp
    ../game/render/Culling/SpatialTree.cpp
    ../game/render/Culling/SpatialTreeIter.cpp
    ../game/render/Culling/SphereSP.cpp
    ../game/render/Culling/VectorLib.cpp
    ../game/render/Culling/WorldScene.cpp
    ../game/render/DSG/DSGFactory.cpp
    ../game/render/DSG/DynaPhysDSG.cpp
    ../game/render/DSG/FenceEntityDSG.cpp
    ../game/render/DSG/IEntityDSG.cpp
    ../game/render/DSG/InstAnimDynaPhysDSG.cpp
    ../game/render/DSG/InstDynaPhysDSG.cpp
    ../game/render/DSG/InstStatEntityDSG.cpp
    ../game/render/DSG/InstStatPhysDSG.cpp
    ../game/render/DSG/IntersectDSG.cpp
    ../game/render/DSG/LensFlareDSG.cpp
    ../game/render/DSG/StatePropDSG.cpp
    ../game/render/DSG/StaticEntityDSG.cpp
    ../game/render/DSG/StaticPhysDSG.cpp
    ../game/render/DSG/TriStripDSG.cpp
    ../game/render/DSG/WorldSphereDSG.cpp
    ../game/render/DSG/animcollisionentitydsg.cpp
    ../game/render/DSG/animentitydsg.cpp
    ../game/render/DSG/breakableobjectdsg.cpp
    ../game/render/DSG/collisionentitydsg.cpp
    ../game/render/IntersectManager/IntersectManager.cpp
    ../game/render/Loaders/AllWrappers.cpp
    ../game/render/Loaders/AnimCollLoader.cpp
    ../game/render/Loaders/AnimDSGLoader.cpp
    ../game/render/Loaders/AnimDynaPhysLoader.cpp
    ../game/render/Loaders/BillboardWrappedLoader.cpp
    ../game/render/Loaders/DynaPhysLoader.cpp
    ../game/render/Loaders/FenceLoader.cpp
    ../game/render/Loaders/GeometryWrappedLoader.cpp
    ../game/render/Loaders/InstStatEntityLoader.cpp
    ../game/render/Loaders/InstStatPhysLoader.cpp
    ../game/render/Loaders/IntersectLoader.cpp
    ../game/render/Loaders/LensFlareLoader.cpp
    ../game/render/Loaders/StaticEntityLoader.cpp
    ../game/render/Loaders/StaticPhysLoader.cpp
    ../game/render/Loaders/TreeDSGLoader.cpp
    ../game/render/Loaders/WorldSphereLoader.cpp
    ../game/render/Loaders/breakableobjectloader.cpp
    ../game/render/Loaders/instparticlesystemloader.cpp
    ../game/render/Particles/particlemanager.cpp
    ../game/render/Particles/particlesystemdsg.cpp
    ../game/render/Particles/vehicleparticleemitter.cpp
    ../game/render/RenderFlow/renderflow.cpp
    ../game/render/RenderManager/FrontEndRenderLayer.cpp
    ../game/render/RenderManager/RenderLayer.cpp
    ../game/render/RenderManager/RenderManager.cpp
    ../game/render/RenderManager/WorldRenderLayer.cpp
    ../game/render/animentitydsgmanager/animentitydsgmanager.cpp
    ../game/render/breakables/breakablesmanager.cpp
    ../game/roads/geometry.cpp
    ../game/roads/intersection.cpp
    ../game/roads/lane.cpp
    ../game/roads/road.cpp
    ../game/roads/roadmanager.cpp
    ../game/roads/roadrender.cpp
    ../game/roads/roadrendertest.cpp
    ../game/roads/roadsegment.cpp
    ../game/roads/roadsegmentdata.cpp
    ../game/roads/trafficcontrol.cpp
    ../game/sound/avatar/avatarsoundplayer.cpp
    ../game/sound/avatar/carsoundparameters.cpp
    ../game/sound/avatar/soundavatar.cpp
    ../game/sound/avatar/vehiclesounddebugpage.cpp
    ../game/sound/avatar/vehiclesoundplayer.cpp
    ../game/sound/dialog/conversation.cpp
    ../game/sound/dialog/conversationmatcher.cpp
    ../game/sound/dialog/dialogcoordinator.cpp
    ../game/sound/dialog/dialogline.cpp
    ../game/sound/dialog/dialoglist.cpp
    ../game/sound/dialog/dialogpriorityqueue.cpp
    ../game/sound/dialog/dialogqueueelement.cpp
    ../game/sound/dialog/dialogselectiongroup.cpp
    ../game/sound/dialog/dialogsounddebugpage.cpp
    ../game/sound/dialog/playabledialog.cpp
    ../game/sound/dialog/selectabledialog.cpp
    ../game/sound/listener.cpp
    ../game/sound/movingpositional/actorplayer.cpp
    ../game/sound/movingpositional/aivehiclesoundplayer.cpp
    ../game/sound/movingpositional/animobjsoundplayer.cpp
    ../game/sound/movingpositional/avatarvehicleposnplayer.cpp
    ../game/sound/movingpositional/movingsoundmanager.cpp
    ../game/sound/movingpositional/platformsoundplayer.cpp
    ../game/sound/movingpositional/trafficsoundplayer.cpp
    ../game/sound/movingpositional/vehicleposnsoundplayer.cpp
    ../game/sound/movingpositional/waspsoundplayer.cpp
    ../game/sound/music/musicplayer.cpp
    ../game/sound/nis/nissoundplayer.cpp
    ../game/sound/positionalsoundplayer.cpp
    ../game/sound/simpsonssoundplayer.cpp
    ../game/sound/soundcluster.cpp
    ../game/sound/sounddebug/sounddebugdisplay.cpp
    ../game/sound/sounddebug/sounddebugpage.cpp
    ../game/sound/soundfx/positionalsoundsettings.cpp
    ../game/sound/soundfx/reverbcontroller.cpp
    ../game/sound/soundfx/reverbsettings.cpp
    ../game/sound/soundfx/soundeffectplayer.cpp
    ../game/sound/soundfx/soundfxfrontendlogic.cpp
    ../game/sound/soundfx/soundfxgameplaylogic.cpp
    ../game/sound/soundfx/soundfxlogic.cpp
    ../game/sound/soundfx/soundfxpauselogic.cpp
    ../game/sound/soundfx/win32reverbcontroller.cpp
    ../game/sound/soundloader.cpp
    ../game/sound/soundmanager.cpp
    ../game/sound/soundrenderer/dasoundplayer.cpp
    ../game/sound/soundrenderer/fader.cpp
    ../game/sound/soundrenderer/musicsoundplayer.cpp
    ../game/sound/soundrenderer/playermanager.cpp
    ../game/sound/soundrenderer/scripts/apu.cpp
    ../game/sound/soundrenderer/scripts/bart.cpp
    ../game/sound/soundrenderer/scripts/cars.cpp
    ../game/sound/soundrenderer/scripts/effects.cpp
    ../game/sound/soundrenderer/scripts/english.cpp
    ../game/sound/soundrenderer/scripts/homer.cpp
    ../game/sound/soundrenderer/scripts/levels.cpp
    ../game/sound/soundrenderer/scripts/lisa.cpp
    ../game/sound/soundrenderer/scripts/marge.cpp
    ../game/sound/soundrenderer/scripts/tuning.cpp
    ../game/sound/soundrenderer/soundallocatedresource.cpp
    ../game/sound/soundrenderer/sounddynaload.cpp
    ../game/sound/soundrenderer/soundnucleus.cpp
    ../game/sound/soundrenderer/soundrenderingmanager.cpp
    ../game/sound/soundrenderer/soundresource.cpp
    ../game/sound/soundrenderer/soundresourcemanager.cpp
    ../game/sound/soundrenderer/soundtuner.cpp
    ../game/sound/soundrenderer/tunerdebugpage.cpp
    ../game/sound/soundrenderer/wireplayers.cpp
    ../game/sound/soundrenderer/wiresystem.cpp
    ../game/sound/soundrenderercallback.cpp
    ../game/sound/tuning/globalsettings.cpp
    ../game/stateprop/stateprop.cpp
    ../game/stateprop/statepropdata.cpp
    ../game/supersprint/supersprintdata.cpp
    ../game/supersprint/supersprintmanager.cpp
    ../game/worldsim/avatar.cpp
    ../game/worldsim/avatarmanager.cpp
    ../game/worldsim/character/aicharactercontroller.cpp
    ../game/worldsim/character/character.cpp
    ../game/worldsim/character/charactercontroller.cpp
    ../game/worldsim/character/charactermanager.cpp
    ../game/worldsim/character/charactermappable.cpp
    ../game/worldsim/character/characterrenderable.cpp
    ../game/worldsim/character/charactertarget.cpp
    ../game/worldsim/character/footprint/footprint.cpp
    ../game/worldsim/character/footprint/footprintmanager.cpp
    ../game/worldsim/coins/coinmanager.cpp
    ../game/worldsim/coins/sparkle.cpp
    ../game/worldsim/groundplanepool.cpp
    ../game/worldsim/harass/chasemanager.cpp
    ../game/worldsim/hitnrunmanager.cpp
    ../game/worldsim/huskpool.cpp
    ../game/worldsim/parkedcars/parkedcarmanager.cpp
    ../game/worldsim/ped/pedestrian.cpp
    ../game/worldsim/ped/pedestrianmanager.cpp
    ../game/worldsim/redbrick/geometryvehicle.cpp
    ../game/worldsim/redbrick/physicslocomotion.cpp
    ../game/worldsim/redbrick/physicslocomotioncontrollerforces.cpp
    ../game/worldsim/redbrick/redbrickcollisionsolveragent.cpp
    ../game/worldsim/redbrick/rootmatrixdriver.cpp
    ../game/worldsim/redbrick/suspensionjointdriver.cpp
    ../game/worldsim/redbrick/trafficbodydrawable.cpp
    ../game/worldsim/redbrick/trafficlocomotion.cpp
    ../game/worldsim/redbrick/vehicle.cpp
    ../game/worldsim/redbrick/vehiclecontroller/aivehiclecontroller.cpp
    ../game/worldsim/redbrick/vehiclecontroller/humanvehiclecontroller.cpp
    ../game/worldsim/redbrick/vehiclecontroller/vehiclecontroller.cpp
    ../game/worldsim/redbrick/vehiclecontroller/vehiclemappable.cpp
    ../game/worldsim/redbrick/vehicleeventlistener.cpp
    ../game/worldsim/redbrick/vehicleinit.cpp
    ../game/worldsim/redbrick/vehiclelocomotion.cpp
    ../game/worldsim/redbrick/wheel.cpp
    ../game/worldsim/skidmarks/SkidMarkGenerator.cpp
    ../game/worldsim/skidmarks/skidmark.cpp
    ../game/worldsim/skidmarks/skidmarkmanager.cpp
    ../game/worldsim/spawn/spawnmanager.cpp
    ../game/worldsim/traffic/trafficmanager.cpp
    ../game/worldsim/vehiclecentral.cpp
    ../game/worldsim/worldcollisionsolveragent.cpp
    ../game/worldsim/worldobject.cpp
    ../game/worldsim/worldphysicsmanager.cpp)

if(WIN32)
    list(APPEND SRR2_SOURCES
        ../game/input/basedamper.cpp
        ../game/input/constanteffect.cpp
        ../game/input/forceeffect.cpp
        ../game/input/steeringspring.cpp
        ../game/input/wheelrumble.cpp)
endif()

if(APPLE)
    list(APPEND SRR2_SOURCES
)
endif()
